language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: WDMUiNslmeZjbiHczNFPP8wbFc70XGsvsW35SRlcV/To9GSkWVJHVj/J1EjINrVfAuDZcXeWD/kpGRDRnF7ySEvxI5kBjrf2yJcPC51ytQHvYYr85Y9920htJbyG+v4yYFVE4buEuG2YRtI0/e1f7c09U7zqnvEt/9fF0595gLuhO2xGIrXnxn1VpsLjdPxUTru0EyjgIjyerdunrYLdcoU5QoUuEKgA0+9nzDF366F1ZeC8XQ854ZYVv7JqSwGZZFqwYKa4TCoJhxrllTDMBY27nyXGHXY8ZJKWQs/2K+BJSmV/aJsEAlbs/YOfL+uWbIPUBxZEtnpadTw1UsKoN2svG1a3rcCGA6tHXaN46ILcdDtOYlYPe4zZfCDkiJYtY6WLkIbR3usB3PBsEolEmiklasq2V1kSz9G0idSIJgF329t+t8YWOuRQsaqBdlciTEXc7z4go1BHb+Ox9FPL7G+m6QG8wwxkVNm2TYE/q/khsmtlQkj1EQlmK0+0l7TieM1SghYhcGqDHW3EUi5fzDlQjnavJk6eoLTTgy5nog/a1L4tAMdGmpHfR90an987Ln25Cx/u7J6/zwTqiXyjWQkTw9PmQ/G7oj2d4kguxjqkq1Z48/kNAXfELnnpQQfyHiQygLOtM37wAzahRo136i2LS+zmMiO4RA/3Vghhj/M=
  app: hangmanatee-api
  on:
    repo: soundofsilence75/hangmanatee-api
